Limit Border Size 200 (MAX) and content overflow visiblity hidden
rutikwankhade/CoverView pull request #10
Opened 2020-10-07 09:15 UTC by Rajakumardev

### **Limit Border Size**

**_Why this Pull Request ?_**

This pull request solves the [issue#8](https://github.com/rutikwankhade/CoverView/issues/8)

**Changes**

1. Limit Border Size (MAX 200)
2. Set the content overflow to hidden for cover(element)

_Thanks_

2020-10-07 12:14 UTC, rutikwankhade requested changes
200 looks too much. I think the max value should be limited to utmost 50.

2020-10-07 13:38 UTC, Rajakumardev commented
**Changes**

1. Changed Max value to 50.
2. `maxBorderValidationCheck()` - to check the value is greater than 50 and scale down to 50 if it is greater (this will prevent users to type the value greater than 50 directly).

2020-10-08 14:34 UTC, rutikwankhade approved these changes

2020-10-08 14:36 UTC, rutikwankhade commented
Perfect. Thanks, @Rajakumardev for contributing. 👍

2020-10-08 14:37 UTC, merged